# Generated by Django 4.0.1 on 2022-02-14 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score_li',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator('0.0'), django.core.validators.MaxValueValidator('3.0')]),
        ),
        migrations.AddField(
            model_name='rating',
            name='score_sm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator('0.0'), django.core.validators.MaxValueValidator('3.0')]),
        ),
        migrations.AddField(
            model_name='rating',
            name='score_so',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator('0.0'), django.core.validators.MaxValueValidator('3.0')]),
        ),
        migrations.AddField(
            model_name='rating',
            name='score_sp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator('0.0'), django.core.validators.MaxValueValidator('3.0')]),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'place'), name='rating_once'),
        ),
    ]
