# Generated by Django 4.0.1 on 2022-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rating_score_li_rating_score_sm_rating_score_so_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='score_avg',
            field=models.FloatField(verbose_name='Average Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_li',
            field=models.FloatField(verbose_name='Light Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_sm',
            field=models.FloatField(verbose_name='Smell Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_so',
            field=models.FloatField(verbose_name='Sound Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_sp',
            field=models.FloatField(verbose_name='Spaciousness Score'),
        ),
    ]
