# Generated by Django 4.0.1 on 2022-02-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_score_avg_alter_place_score_li_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
