# Generated by Django 4.0.1 on 2022-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Review Count'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Pizzeria', 'Pizzeria'), ('Cafe', 'Cafe'), ('Fastfood', 'Fast food'), ('Other', 'Other')], max_length=30, verbose_name='Tag'),
        ),
    ]
