# Generated by Django 4.0.1 on 2022-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_review_count_alter_place_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_once',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('created_by', 'place'), name='rating_once'),
        ),
    ]
