# Generated by Django 4.0.1 on 2022-02-15 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_remove_rating_rating_once_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('score_avg', models.FloatField(default=0, verbose_name='Average rating')),
                ('score_li', models.CharField(choices=[('N/A', 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20, verbose_name='Light intensity score')),
                ('score_so', models.CharField(choices=[('N/A', 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20, verbose_name='Sound intensity score')),
                ('score_sp', models.IntegerField(choices=[('N/A', 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Spaciousness score')),
                ('score_sm', models.IntegerField(choices=[('N/A', 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Smell intensity score')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'place'), name='One rating per place'),
        ),
    ]
