# Generated by Django 4.0.1 on 2022-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_location_alter_review_score_li_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_li',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Light intensity score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_so',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Sound intensity score'),
        ),
    ]
