# Generated by Django 4.0.1 on 2022-02-17 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_review_score_li_alter_review_score_so'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='One rating per place',
        ),
        migrations.AlterField(
            model_name='place',
            name='score_avg',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Average Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_li',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Light Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_sm',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Smell Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_so',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sound Intensity Score'),
        ),
        migrations.AlterField(
            model_name='place',
            name='score_sp',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Spaciousness Score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_li',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Light intensity score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_sm',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Smell intensity score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_so',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sound intensity score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_sp',
            field=models.IntegerField(choices=[(0, 'Do not know'), (1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Spaciousness score'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'place'), name='One review per place'),
        ),
    ]
