# Generated by Django 4.0.1 on 2022-02-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_review_one rating per place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='review_count',
        ),
    ]
