# Generated by Django 4.1.1 on 2022-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_place_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(choices=[('WBIE', 'Warszawa-Bielany'), ('WCEN', 'Warszawa-Centrum'), ('WOCH', 'Warszawa-Ochota'), ('WTAR', 'Warszawa-Targówek'), ('WMOK', 'Warszawa-Mokotów'), ('WWOL', 'Warszawa-Wola')], default='Other', max_length=4, verbose_name='Location'),
        ),
    ]
