# Generated by Django 4.1.1 on 2022-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='score_avg',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_avg',
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(choices=[('WBIE', 'Warszawa-Bielany'), ('WCEN', 'Warszawa-Centrum'), ('WOCH', 'Warszawa-Ochota'), ('WTAR', 'Warszawa-Targówek'), ('WMOK', 'Warszawa-Mokotów'), ('WWOL', 'Warszawa-Wola')], default=('OTHER', 'Other'), max_length=4, verbose_name='Location'),
        ),
    ]
