# Generated by Django 4.1.1 on 2022-10-01 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_remove_place_score_li_remove_place_score_sm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lsi',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Low-sight friendly'),
        ),
        migrations.AlterField(
            model_name='review',
            name='noi',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Noise'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sin',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sensory intensity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='wac',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Wheelchair accessibility'),
        ),
    ]
