# Generated by Django 4.1.1 on 2022-09-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_preferences_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preferences',
            name='One Entry Per User',
        ),
    ]
